version: '3'

services:
  productRegistrationApi:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: optimaltech-docker:0.1
    container_name: productRegistrationApi
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - URL_CLIENT=${URL_CLIENT}

  db:
    image: postgres:14
    container_name: optimalTechDb
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data